import { DroneModel } from "@/types/drone";

export const DRONES: DroneModel[] = [
  {
    id: "aero-trainer-x4",
    platformId: "quadcopter",
    platformCategory: "Multirotor",
    missionCategory: "Training",
    name: "AeroTrainer Quad X4",
    tagline: "4 Rotors • Stable Hover",
    description: "Designed for pilot training and basic flight instruction.",
    whyThisAircraft: "Quadcopters are stable, maneuverable VTOL aircraft. This configuration is perfectly balanced for learning flight dynamics without overwhelming the pilot.",
    image: "/drone1.png",
    badge: "Class 4A",
    baseMassKg: 2.55,
    batteryCells: 4,
    defaultPayloadKg: 0.0,
    sensors: ["GPS", "IMU", "Barometer", "Compass"],
  },
  {
    id: "agrispray-x4",
    platformId: "quadcopter",
    platformCategory: "Multirotor",
    missionCategory: "Agriculture",
    name: "AgriSpray Quad X4",
    tagline: "4 Rotors • Precision Spraying",
    description: "A modified quadcopter platform equipped with lightweight agricultural spraying systems.",
    whyThisAircraft: "This provides a highly agile platform for precision spot-spraying in tight agricultural environments where larger hexacopters cannot easily maneuver.",
    image: "/drone1.png",
    badge: "Class 4B",
    baseMassKg: 4.2,
    batteryCells: 6,
    defaultPayloadKg: 2.5,
    sensors: ["RTK GPS", "IMU", "LiDAR Altimeter", "Compass"],
  },
  {
    id: "skymapper-6b",
    platformId: "hexacopter",
    platformCategory: "Multirotor",
    missionCategory: "Mapping",
    name: "SkyMapper Hexa 6B",
    tagline: "6 Rotors • Enhanced Stability",
    description: "Radial 6-motor layout offering motor redundancy and increased lift stability for photogrammetry.",
    whyThisAircraft: "Hexacopters offer superior stability in crosswinds and provide motor-out redundancy, which is critical when flying expensive surveying payloads.",
    image: "/drone2.png",
    badge: "Class 6B",
    baseMassKg: 6.8,
    batteryCells: 6,
    defaultPayloadKg: 1.5,
    sensors: ["RTK GPS", "IMU", "Barometer", "Compass", "Optical Flow"],
  },
  {
    id: "inspection-hex",
    platformId: "hexacopter",
    platformCategory: "Multirotor",
    missionCategory: "Inspection",
    name: "Inspection Hexa-Core",
    tagline: "6 Rotors • Close-Proximity",
    description: "Industrial inspection drone optimized for vertical infrastructure assessment.",
    whyThisAircraft: "Features a top-mounted gimbal option and robust obstacle avoidance, allowing safe operation near bridges, wind turbines, and power lines.",
    image: "/drone2.png",
    badge: "Class 6C",
    baseMassKg: 7.2,
    batteryCells: 8,
    defaultPayloadKg: 1.8,
    sensors: ["RTK GPS", "Dual IMU", "Stereo Vision", "Compass"],
  },
  {
    id: "titan-octo-8c",
    platformId: "octacopter",
    platformCategory: "Multirotor",
    missionCategory: "Delivery",
    name: "Titan Octo 8C Industrial",
    tagline: "8 Rotors • Heavy Payload",
    description: "Industrial 8-rotor heavy lifter with maximum thrust authority for logistics.",
    whyThisAircraft: "Octocopters provide maximum lift capacity and redundancy. This platform is designed to securely transport heavy cargo over short to medium distances.",
    image: "/drone3.png",
    badge: "Class 8C",
    baseMassKg: 12.5,
    batteryCells: 12,
    defaultPayloadKg: 8.0,
    sensors: ["Dual RTK GPS", "Triple IMU", "LiDAR", "Compass"],
  },
  {
    id: "rescue-octo",
    platformId: "octacopter",
    platformCategory: "Multirotor",
    missionCategory: "Emergency",
    name: "Overwatch SAR-8",
    tagline: "8 Rotors • Search & Rescue",
    description: "Rapid-deployment emergency response multirotor equipped with thermal imaging.",
    whyThisAircraft: "Capable of carrying heavy thermal payloads while fighting high winds, making it ideal for disaster response and search operations.",
    image: "/drone3.png",
    badge: "Class 8C",
    baseMassKg: 14.0,
    batteryCells: 12,
    defaultPayloadKg: 3.5,
    sensors: ["RTK GPS", "Dual IMU", "Thermal Sensor", "Spotlight"],
  },
];

export const DEFAULT_DRONE_STORAGE_KEY = "drone_pilot_selected_drone";

export function getDroneById(id: string): DroneModel | undefined {
  return DRONES.find((d) => d.id === id);
}
