import React from "react";
import { Download, X, Clock, Navigation, AlertTriangle, ShieldCheck, Activity, CloudSun } from "lucide-react";
import { DroneModel } from "@/types/drone";
import { TelemetryState, EnvironmentState } from "@/lib/simulation/types";
import { FlightCoachInsight } from "@/lib/simulation/flight-coach-types";

interface Stats {
  startTime: number;
  topSpeed: number;
  maxAltitude: number;
  distance: number;
  crashes: number;
}

interface Props {
  drone: DroneModel;
  telemetry: TelemetryState;
  envState: EnvironmentState;
  stats: Stats;
  insights: FlightCoachInsight[];
  onClose: () => void;
}

export function PostFlightReportModal({ drone, telemetry, envState, stats, insights, onClose }: Props) {
  const flightTimeSec = Math.round((Date.now() - stats.startTime) / 1000);
  const flightTimeStr = `${Math.floor(flightTimeSec / 60)}m ${flightTimeSec % 60}s`;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm print:bg-white print:backdrop-blur-none p-4 sm:p-8">
      <div className="relative w-full max-w-4xl max-h-[90vh] bg-white text-black rounded-2xl shadow-2xl overflow-y-auto print:max-h-none print:shadow-none print:w-full print:border-none print:rounded-none flex flex-col">
        
        {/* Web UI Actions (Hidden in Print) */}
        <div className="sticky top-0 z-10 flex justify-between items-center bg-white/90 backdrop-blur border-b border-gray-200 px-6 py-4 print:hidden">
          <h2 className="font-black text-xl tracking-tight text-neutral-800">SIMULATION REPORT</h2>
          <div className="flex gap-3">
            <button
              onClick={() => window.print()}
              className="flex items-center gap-2 px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-bold text-sm transition-colors"
            >
              <Download className="w-4 h-4" /> Download PDF
            </button>
            <button
              onClick={onClose}
              className="p-2 rounded-lg bg-neutral-100 hover:bg-neutral-200 text-neutral-600 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Report Content (Printable) */}
        <div className="p-8 sm:p-12 space-y-10">
          
          {/* Header */}
          <div className="border-b-4 border-neutral-900 pb-6 mb-8 flex justify-between items-end">
            <div>
              <h1 className="text-4xl font-black tracking-tighter text-neutral-900 uppercase">POST-FLIGHT ANALYTICS</h1>
              <p className="text-neutral-500 font-medium mt-2">Generated by Drone Pilot Simulator</p>
            </div>
            <div className="text-right">
              <p className="text-lg font-bold text-neutral-800">{new Date().toLocaleDateString()}</p>
              <p className="text-sm text-neutral-500">{new Date().toLocaleTimeString()}</p>
            </div>
          </div>

          {/* Aircraft & Environment */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="bg-neutral-50 p-6 rounded-xl border border-neutral-200">
              <h3 className="text-sm font-bold tracking-widest text-neutral-500 uppercase mb-4 flex items-center gap-2">
                <Navigation className="w-4 h-4" /> Aircraft Profile
              </h3>
              <p className="text-2xl font-black text-neutral-800 mb-1">{drone.name}</p>
              <p className="text-neutral-600 font-medium">{drone.platformCategory} - {drone.baseMassKg}kg</p>
              <div className="mt-4 pt-4 border-t border-neutral-200 grid grid-cols-2 gap-4">
                <div>
                  <p className="text-xs text-neutral-500 uppercase font-bold">Remaining Battery</p>
                  <p className="text-lg font-black text-neutral-800">{Math.round(telemetry.batteryLevel)}%</p>
                </div>
                <div>
                  <p className="text-xs text-neutral-500 uppercase font-bold">Total Flight Distance</p>
                  <p className="text-lg font-black text-neutral-800">{Math.round(stats.distance)}m</p>
                </div>
              </div>
            </div>

            <div className="bg-neutral-50 p-6 rounded-xl border border-neutral-200">
              <h3 className="text-sm font-bold tracking-widest text-neutral-500 uppercase mb-4 flex items-center gap-2">
                <CloudSun className="w-4 h-4" /> Environmental Conditions
              </h3>
              <div className="grid grid-cols-2 gap-y-4">
                <div>
                  <p className="text-xs text-neutral-500 uppercase font-bold">Wind Speed</p>
                  <p className="text-lg font-black text-neutral-800">{envState.windSpeed.toFixed(1)} m/s</p>
                </div>
                <div>
                  <p className="text-xs text-neutral-500 uppercase font-bold">Turbulence</p>
                  <p className="text-lg font-black text-neutral-800">{Math.round((envState.turbulence || 0) * 100)}%</p>
                </div>
                <div>
                  <p className="text-xs text-neutral-500 uppercase font-bold">Precipitation</p>
                  <p className="text-lg font-black text-neutral-800">{Math.round((envState.rainIntensity || 0) * 100)}%</p>
                </div>
                <div>
                  <p className="text-xs text-neutral-500 uppercase font-bold">Air Temp</p>
                  <p className="text-lg font-black text-neutral-800">{envState.temperature}AC</p>
                </div>
              </div>
            </div>
          </div>

          {/* Core Metrics */}
          <div>
            <h3 className="text-sm font-bold tracking-widest text-neutral-500 uppercase mb-4">Flight Performance Metrics</h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="p-4 bg-white border-2 border-neutral-100 rounded-xl text-center">
                <Clock className="w-6 h-6 text-blue-500 mx-auto mb-2" />
                <p className="text-xs text-neutral-500 uppercase font-bold">Time in Air</p>
                <p className="text-xl font-black text-neutral-800">{flightTimeStr}</p>
              </div>
              <div className="p-4 bg-white border-2 border-neutral-100 rounded-xl text-center">
                <Activity className="w-6 h-6 text-emerald-500 mx-auto mb-2" />
                <p className="text-xs text-neutral-500 uppercase font-bold">Max Altitude</p>
                <p className="text-xl font-black text-neutral-800">{Math.round(stats.maxAltitude)}m</p>
              </div>
              <div className="p-4 bg-white border-2 border-neutral-100 rounded-xl text-center">
                <Navigation className="w-6 h-6 text-purple-500 mx-auto mb-2" />
                <p className="text-xs text-neutral-500 uppercase font-bold">Top Speed</p>
                <p className="text-xl font-black text-neutral-800">{Math.round(stats.topSpeed)} m/s</p>
              </div>
              <div className={`p-4 bg-white border-2 rounded-xl text-center ${stats.crashes > 0 ? 'border-rose-100 bg-rose-50' : 'border-neutral-100'}`}>
                {stats.crashes > 0 ? <AlertTriangle className="w-6 h-6 text-rose-500 mx-auto mb-2" /> : <ShieldCheck className="w-6 h-6 text-emerald-500 mx-auto mb-2" />}
                <p className="text-xs text-neutral-500 uppercase font-bold">Incidents (Crashes)</p>
                <p className="text-xl font-black text-neutral-800">{stats.crashes}</p>
              </div>
            </div>
          </div>

          {/* Flight Coach Analysis */}
          <div>
            <h3 className="text-sm font-bold tracking-widest text-neutral-500 uppercase mb-4">Pilot Evaluation & Areas for Improvement</h3>
            {insights.length === 0 ? (
              <div className="bg-emerald-50 border border-emerald-200 rounded-xl p-6 text-center">
                <ShieldCheck className="w-8 h-8 text-emerald-500 mx-auto mb-2" />
                <p className="font-bold text-emerald-800 text-lg">Excellent Flight Performance</p>
                <p className="text-emerald-600 text-sm mt-1">No critical pilot errors or unsafe maneuvers were detected during this session.</p>
              </div>
            ) : (
              <div className="space-y-4">
                {insights.slice().reverse().map((insight, i) => (
                  <div key={i} className="bg-white border border-neutral-200 rounded-xl p-5 shadow-sm">
                    <div className="flex items-start gap-4">
                      <div className={`p-2 rounded-lg mt-1 ${
                        insight.severity === 'CRITICAL' ? 'bg-rose-100 text-rose-600' :
                        insight.severity === 'ATTENTION' ? 'bg-amber-100 text-amber-600' : 'bg-blue-100 text-blue-600'
                      }`}>
                        <AlertTriangle className="w-5 h-5" />
                      </div>
                      <div>
                        <h4 className="font-bold text-neutral-900 text-base">{insight.title}</h4>
                        <p className="text-sm text-neutral-600 mt-1">{insight.explanation.what}</p>
                        <div className="mt-3 bg-neutral-50 rounded-lg p-3 text-sm">
                          <span className="font-bold text-neutral-700">Recommendation:</span> <span className="text-neutral-600">{insight.explanation.learn}</span>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

        </div>
      </div>
    </div>
  );
}
