// ==========================================================
// DRONE PILOT — CANONICAL REGION REGISTRY
// Definitions for all 8 connected simulation zones
// ==========================================================

import { RegionDefinition } from "./world-types";

export const REGIONS: Record<string, RegionDefinition> = {
  training: {
    id: "training",
    name: "Central Flight Academy",
    shortName: "Academy",
    category: "academy",
    description: "Primary training plateau with obstacle arenas, runway lighting, and open airspace.",
    center: { x: 0, y: 1.2, z: 0 },
    bounds: { minX: -180, maxX: 180, minZ: -180, maxZ: 180 },
    elevationRange: { min: 1.2, max: 2.0 },
    mapColor: "#f59e0b",
    primaryHelipadId: "training-alpha",
    helipadIds: ["training-alpha", "training-bravo"],
    environment: {
      baseWindSpeedMs: 2.5,
      windDirectionDeg: 65,
      gustFactor: 0.1,
      airTemperatureC: 22,
      airDensity: 1.225,
      visibilityKm: 12,
    },
  },

  forest: {
    id: "forest",
    name: "Whispering Pines Forest",
    shortName: "Forest",
    category: "nature",
    description: "Expansive multi-species woodland with natural canopy gaps, granite boulders, and slalom trails.",
    center: { x: 450, y: 4.0, z: -420 },
    bounds: { minX: 220, maxX: 780, minZ: -720, maxZ: -180 },
    elevationRange: { min: 2.0, max: 9.0 },
    mapColor: "#16a34a",
    primaryHelipadId: "forest-alpha",
    helipadIds: ["forest-alpha"],
    environment: {
      baseWindSpeedMs: 1.8,
      windDirectionDeg: 45,
      gustFactor: 0.15,
      airTemperatureC: 19,
      airDensity: 1.23,
      visibilityKm: 8,
    },
  },

  mountain: {
    id: "mountain",
    name: "Mount Apex Highlands",
    shortName: "Mountains",
    category: "highlands",
    description: "Towering craggy massif with 8 rocky peaks up to 85m, permanent snow caps, and high-altitude winds.",
    center: { x: -480, y: 24.0, z: -450 },
    bounds: { minX: -820, maxX: -200, minZ: -750, maxZ: -200 },
    elevationRange: { min: 12.0, max: 85.0 },
    mapColor: "#64748b",
    primaryHelipadId: "mountain-alpha",
    helipadIds: ["mountain-alpha"],
    environment: {
      baseWindSpeedMs: 6.2,
      windDirectionDeg: 320,
      gustFactor: 0.35,
      airTemperatureC: 11,
      airDensity: 1.18,
      visibilityKm: 15,
    },
  },

  river: {
    id: "river",
    name: "Valley River & Canyon",
    shortName: "River Valley",
    category: "freshwater",
    description: "Scenic freshwater channel carved from mountain runoff passing beneath arched bridges into the ocean delta.",
    center: { x: -120, y: 1.5, z: 120 },
    bounds: { minX: -300, maxX: 80, minZ: -100, maxZ: 360 },
    elevationRange: { min: 0.5, max: 4.5 },
    mapColor: "#0284c7",
    primaryHelipadId: "river-alpha",
    helipadIds: ["river-alpha"],
    environment: {
      baseWindSpeedMs: 3.0,
      windDirectionDeg: 190,
      gustFactor: 0.2,
      airTemperatureC: 20,
      airDensity: 1.225,
      visibilityKm: 10,
    },
  },

  city: {
    id: "city",
    name: "Downtown Metropolis",
    shortName: "Metropolis",
    category: "urban",
    description: "Dense commercial skyscraper district with narrow flight corridors, rooftop helipads, and communications mast.",
    center: { x: 520, y: 2.5, z: 380 },
    bounds: { minX: 280, maxX: 820, minZ: 160, maxZ: 680 },
    elevationRange: { min: 1.5, max: 62.0 },
    mapColor: "#3b82f6",
    primaryHelipadId: "city-alpha",
    helipadIds: ["city-alpha", "city-apex-rooftop"],
    environment: {
      baseWindSpeedMs: 4.5,
      windDirectionDeg: 120,
      gustFactor: 0.25,
      airTemperatureC: 23,
      airDensity: 1.22,
      visibilityKm: 12,
    },
  },

  industrial: {
    id: "industrial",
    name: "Harbor Industrial Park",
    shortName: "Industrial",
    category: "logistics",
    description: "Shipping terminal with aircraft hangars, fuel silos, intermodal container stacks, and overhead piping.",
    center: { x: 120, y: 1.8, z: 620 },
    bounds: { minX: -80, maxX: 340, minZ: 440, maxZ: 820 },
    elevationRange: { min: 1.2, max: 14.0 },
    mapColor: "#d97706",
    primaryHelipadId: "industrial-alpha",
    helipadIds: ["industrial-alpha"],
    environment: {
      baseWindSpeedMs: 3.8,
      windDirectionDeg: 150,
      gustFactor: 0.18,
      airTemperatureC: 22,
      airDensity: 1.225,
      visibilityKm: 10,
    },
  },

  coast: {
    id: "coast",
    name: "Pelican Coves & Bluffs",
    shortName: "Coastline",
    category: "maritime",
    description: "Sweeping sandy crescent beaches, rocky headland bluffs, sea stacks, and coastal rescue station.",
    center: { x: -580, y: 1.5, z: 320 },
    bounds: { minX: -850, maxX: -320, minZ: 100, maxZ: 580 },
    elevationRange: { min: 0.3, max: 16.0 },
    mapColor: "#059669",
    primaryHelipadId: "coast-alpha",
    helipadIds: ["coast-alpha"],
    environment: {
      baseWindSpeedMs: 5.0,
      windDirectionDeg: 240,
      gustFactor: 0.22,
      airTemperatureC: 21,
      airDensity: 1.225,
      visibilityKm: 14,
    },
  },

  water: {
    id: "water",
    name: "Archipelago Surrounding Waters",
    shortName: "Ocean",
    category: "ocean",
    description: "Deep open ocean surrounding the island, coastal shallows, navigation buoys, and outer perimeter.",
    center: { x: 0, y: 0, z: 0 },
    bounds: { minX: -2000, maxX: 2000, minZ: -2000, maxZ: 2000 },
    elevationRange: { min: 0.0, max: 0.0 },
    mapColor: "#0284c7",
    primaryHelipadId: "training-alpha",
    helipadIds: [],
    environment: {
      baseWindSpeedMs: 4.8,
      windDirectionDeg: 270,
      gustFactor: 0.2,
      airTemperatureC: 20,
      airDensity: 1.225,
      visibilityKm: 16,
    },
  },
};

export const REGION_LIST = Object.values(REGIONS);
