// ==========================================================
// DRONE PILOT — CANONICAL WORLD DEFINITION (MASTER SPECIFICATION)
// Single Source of Truth for Island Geography, Scale, Regions,
// Landmarks, Road Network, Waterways, and Helipad Infrastructure
// ==========================================================

import {
  WorldDefinition,
  RegionDefinition,
  Helipad,
  LandmarkDefinition,
  RoadNetworkDefinition,
  WaterwayDefinition,
  TerrainConfiguration,
  RegionId,
} from "./world-types";
import { WORLD_CONFIG } from "./world-config";

export const TERRAIN_CONFIG: TerrainConfiguration = {
  worldWidthMeters: WORLD_CONFIG.worldWidth,
  worldLengthMeters: WORLD_CONFIG.worldLength,
  islandWidthMeters: WORLD_CONFIG.islandWidth,
  islandLengthMeters: WORLD_CONFIG.islandLength,
  seaLevelMsl: WORLD_CONFIG.seaLevel,
  maxElevationMsl: WORLD_CONFIG.mountainMaxElevation,
  lakeElevationMsl: WORLD_CONFIG.lakeWaterLevel,
  bathymetryDepthMsl: WORLD_CONFIG.bathymetryDepth,
};

export const REGIONS_RECORD: Record<RegionId, RegionDefinition> = {
  training: {
    id: "training",
    name: "Central Flight Academy",
    shortName: "Academy",
    category: "academy",
    description: "Centrally positioned flight training plateau featuring an asphalt runway, precision landing zones, obstacle arena, and primary apron.",
    center: { x: 0, y: 1.2, z: 0 },
    bounds: { minX: -220, maxX: 220, minZ: -220, maxZ: 220 },
    elevationRange: { min: 1.2, max: 2.8 },
    mapColor: "#f59e0b",
    primaryHelipadId: "training-alpha",
    helipadIds: ["training-alpha", "training-bravo"],
    environment: {
      baseWindSpeedMs: 2.5,
      windDirectionDeg: 65,
      gustFactor: 0.1,
      airTemperatureC: 22,
      airDensity: 1.225,
      visibilityKm: 15,
    },
  },

  forest: {
    id: "forest",
    name: "Whispering Pines Forest",
    shortName: "Forest",
    category: "nature",
    description: "Vast continuous woodland reserve in the western sector with undulating ridges, natural clearings, fire trails, and a ranger lookout tower.",
    center: { x: -640, y: 5.5, z: 20 },
    bounds: { minX: -1000, maxX: -340, minZ: -280, maxZ: 320 },
    elevationRange: { min: 2.5, max: 18.0 },
    mapColor: "#16a34a",
    primaryHelipadId: "forest-alpha",
    helipadIds: ["forest-alpha"],
    environment: {
      baseWindSpeedMs: 1.8,
      windDirectionDeg: 45,
      gustFactor: 0.15,
      airTemperatureC: 19,
      airDensity: 1.23,
      visibilityKm: 10,
    },
  },

  mountain: {
    id: "mountain",
    name: "Mount Apex Massif",
    shortName: "Mountains",
    category: "highlands",
    description: "Dominant northwestern alpine mountain range featuring three connected jagged peaks up to 145m, knife-edge ridges, cirques, scree slopes, and high-altitude weather terrace.",
    center: { x: -650, y: 48.0, z: -650 },
    bounds: { minX: -1100, maxX: -220, minZ: -1120, maxZ: -240 },
    elevationRange: { min: 14.0, max: 145.0 },
    mapColor: "#475569",
    primaryHelipadId: "mountain-alpha",
    helipadIds: ["mountain-alpha"],
    environment: {
      baseWindSpeedMs: 6.8,
      windDirectionDeg: 315,
      gustFactor: 0.38,
      airTemperatureC: 9,
      airDensity: 1.16,
      visibilityKm: 20,
    },
  },

  river: {
    id: "river",
    name: "Valley River & Canyon",
    shortName: "River Valley",
    category: "freshwater",
    description: "Natural geological drainage corridor originating at the alpine lake waterfall, cutting a steep canyon southward under stone arch bridges into the ocean estuary delta.",
    center: { x: -160, y: 3.5, z: 160 },
    bounds: { minX: -360, maxX: 60, minZ: -220, maxZ: 960 },
    elevationRange: { min: 0.2, max: 8.5 },
    mapColor: "#0284c7",
    primaryHelipadId: "river-alpha",
    helipadIds: ["river-alpha"],
    environment: {
      baseWindSpeedMs: 3.2,
      windDirectionDeg: 190,
      gustFactor: 0.2,
      airTemperatureC: 20,
      airDensity: 1.225,
      visibilityKm: 12,
    },
  },

  city: {
    id: "city",
    name: "Downtown Metropolis",
    shortName: "Metropolis",
    category: "urban",
    description: "Dense commercial skyscraper district in the eastern sector, featuring high-rise glass corridors, ground plaza vertiport, and the 68m Apex Tower rooftop skyport.",
    center: { x: 720, y: 2.5, z: 320 },
    bounds: { minX: 420, maxX: 1060, minZ: 80, maxZ: 580 },
    elevationRange: { min: 2.5, max: 68.0 },
    mapColor: "#2563eb",
    primaryHelipadId: "city-alpha",
    helipadIds: ["city-alpha", "city-apex-rooftop"],
    environment: {
      baseWindSpeedMs: 4.8,
      windDirectionDeg: 120,
      gustFactor: 0.28,
      airTemperatureC: 23,
      airDensity: 1.22,
      visibilityKm: 14,
    },
  },

  industrial: {
    id: "industrial",
    name: "Harbor Industrial Park",
    shortName: "Industrial",
    category: "logistics",
    description: "Sprawling maritime cargo and manufacturing district in the southeastern sector with hangars, bulk fuel storage tanks, shipping container yards, and deepwater piers.",
    center: { x: 380, y: 1.8, z: 780 },
    bounds: { minX: 120, maxX: 680, minZ: 560, maxZ: 1040 },
    elevationRange: { min: 1.2, max: 14.0 },
    mapColor: "#d97706",
    primaryHelipadId: "industrial-alpha",
    helipadIds: ["industrial-alpha"],
    environment: {
      baseWindSpeedMs: 4.2,
      windDirectionDeg: 155,
      gustFactor: 0.22,
      airTemperatureC: 22,
      airDensity: 1.225,
      visibilityKm: 12,
    },
  },

  coast: {
    id: "coast",
    name: "Pelican Coves & Bluffs",
    shortName: "Coastline",
    category: "maritime",
    description: "Southwestern maritime frontier showcasing golden crescent beaches, sheer granite sea bluffs rising 22m above crashing surf, offshore sea stacks, and a marine rescue station.",
    center: { x: -720, y: 2.0, z: 580 },
    bounds: { minX: -1080, maxX: -400, minZ: 360, maxZ: 880 },
    elevationRange: { min: 0.3, max: 22.0 },
    mapColor: "#059669",
    primaryHelipadId: "coast-alpha",
    helipadIds: ["coast-alpha"],
    environment: {
      baseWindSpeedMs: 5.5,
      windDirectionDeg: 240,
      gustFactor: 0.25,
      airTemperatureC: 21,
      airDensity: 1.225,
      visibilityKm: 16,
    },
  },

  water: {
    id: "water",
    name: "Archipelago Surrounding Waters",
    shortName: "Ocean",
    category: "ocean",
    description: "Expansive 4.8km open ocean waters, shallow coral reefs, navigation fairway buoys, and outer simulation safety boundary.",
    center: { x: 0, y: 0, z: 0 },
    bounds: { minX: -2400, maxX: 2400, minZ: -2400, maxZ: 2400 },
    elevationRange: { min: -16.0, max: 0.0 },
    mapColor: "#0284c7",
    primaryHelipadId: "training-alpha",
    helipadIds: [],
    environment: {
      baseWindSpeedMs: 5.0,
      windDirectionDeg: 270,
      gustFactor: 0.2,
      airTemperatureC: 20,
      airDensity: 1.225,
      visibilityKm: 18,
    },
  },
};

export const HELIPADS_RECORD: Record<string, Helipad> = {
  "training-alpha": {
    id: "training-alpha",
    regionId: "training",
    name: "Helipad Alpha (Academy Main)",
    position: { x: 0, y: 1.2, z: 0 },
    headingDeg: 0,
    elevation: 1.2,
    dimensions: { width: 14, length: 14, radius: 7 },
    surfaceType: "concrete",
    spawnAllowed: true,
    description: "Primary flight academy operations apron with high-visibility aviation crosshatch markings.",
  },
  "training-bravo": {
    id: "training-bravo",
    regionId: "training",
    name: "Helipad Bravo (Practice Pad)",
    position: { x: 45, y: 1.2, z: 20 },
    headingDeg: 90,
    elevation: 1.2,
    dimensions: { width: 10, length: 10, radius: 5 },
    surfaceType: "concrete",
    spawnAllowed: true,
    description: "Secondary training pad for student hover maneuvers and obstacle course departures.",
  },
  "forest-alpha": {
    id: "forest-alpha",
    regionId: "forest",
    name: "Forest Ranger Station Pad",
    position: { x: -620, y: 5.5, z: -40 },
    headingDeg: 45,
    elevation: 5.5,
    dimensions: { width: 12, length: 12, radius: 6 },
    surfaceType: "wood",
    spawnAllowed: true,
    description: "Elevated timber-framed launch station situated in a pine clearing beside the fire watchtower.",
  },
  "mountain-alpha": {
    id: "mountain-alpha",
    regionId: "mountain",
    name: "Mount Apex Weather Station Pad",
    position: { x: -580, y: 48.0, z: -560 },
    headingDeg: 180,
    elevation: 48.0,
    dimensions: { width: 14, length: 14, radius: 7 },
    surfaceType: "steel",
    spawnAllowed: true,
    description: "High-altitude steel cantilever pad engineered onto a craggy granite ridge overlook with safety railings.",
  },
  "river-alpha": {
    id: "river-alpha",
    regionId: "river",
    name: "Valley Bridge Observation Pad",
    position: { x: -85, y: 10.0, z: 195 },
    headingDeg: 120,
    elevation: 10.0,
    dimensions: { width: 12, length: 12, radius: 6 },
    surfaceType: "concrete",
    spawnAllowed: true,
    description: "Canyon overlook station perched on the high eastern cliff adjacent to the grand suspension bridge.",
  },
  "city-alpha": {
    id: "city-alpha",
    regionId: "city",
    name: "Downtown Heliport Plaza",
    position: { x: 640, y: 2.5, z: 320 },
    headingDeg: 0,
    elevation: 2.5,
    dimensions: { width: 16, length: 16, radius: 8 },
    surfaceType: "concrete",
    spawnAllowed: true,
    description: "Ground-level municipal vertiport terminal nestled between commercial skyscraper towers.",
  },
  "city-apex-rooftop": {
    id: "city-apex-rooftop",
    regionId: "city",
    name: "Apex Center Rooftop Skyport",
    position: { x: 760, y: 68.0, z: 360 },
    headingDeg: 270,
    elevation: 68.0,
    dimensions: { width: 14, length: 14, radius: 7 },
    surfaceType: "rooftop",
    spawnAllowed: true,
    description: "Skyscraper rooftop landing facility for advanced high-altitude rooftop approaches.",
  },
  "industrial-alpha": {
    id: "industrial-alpha",
    regionId: "industrial",
    name: "Harbor Cargo Terminal Pad",
    position: { x: 360, y: 1.8, z: 760 },
    headingDeg: 90,
    elevation: 1.8,
    dimensions: { width: 14, length: 14, radius: 7 },
    surfaceType: "concrete",
    spawnAllowed: true,
    description: "Heavy logistics apron bordered by aircraft hangars, fuel silos, and container yards.",
  },
  "coast-alpha": {
    id: "coast-alpha",
    regionId: "coast",
    name: "Pelican Cove Marine Station Pad",
    position: { x: -720, y: 2.0, z: 560 },
    headingDeg: 315,
    elevation: 2.0,
    dimensions: { width: 12, length: 12, radius: 6 },
    surfaceType: "wood",
    spawnAllowed: true,
    description: "Coastal rescue station pad overlooking turquoise crescent cove and granite sea bluffs.",
  },
};

export const LANDMARKS_RECORD: Record<string, LandmarkDefinition> = {
  "mtn-apex-summit": {
    id: "mtn-apex-summit",
    name: "Mount Apex Summit Peak",
    category: "summit",
    regionId: "mountain",
    position: { x: -620, y: 145.0, z: -720 },
    elevationMsl: 145.0,
    callsign: "APEX-SUMMIT",
    description: "The highest geographic elevation on the island with permanent crags and radio mast.",
  },
  "alpine-lake": {
    id: "alpine-lake",
    name: "Crystal Mountain Lake",
    category: "lake",
    regionId: "river",
    position: { x: -320, y: 8.5, z: -260 },
    elevationMsl: 8.5,
    callsign: "LAKE-RES",
    description: "High mountain reservoir basin collecting alpine runoff and feeding the valley river.",
  },
  "mountain-waterfall": {
    id: "mountain-waterfall",
    name: "Cascade Falls",
    category: "waterfall",
    regionId: "river",
    position: { x: -270, y: 8.5, z: -210 },
    elevationMsl: 8.5,
    callsign: "WATERFALL",
    description: "Dramatic churning plunge where mountain lake water cascades over rocky cliffs into the canyon.",
  },
  "valley-bridge": {
    id: "valley-bridge",
    name: "Grand Valley Suspension Bridge",
    category: "bridge",
    regionId: "river",
    position: { x: -140, y: 9.8, z: 160 },
    elevationMsl: 9.8,
    callsign: "VALLEY-BRG",
    description: "Towering cable-stayed suspension bridge spanning high above the river canyon.",
  },
  "apex-tower": {
    id: "apex-tower",
    name: "Apex Center Skyscraper",
    category: "tower",
    regionId: "city",
    position: { x: 760, y: 68.0, z: 360 },
    elevationMsl: 68.0,
    callsign: "APEX-TOWER",
    description: "Iconic commercial skyscraper crowned with rooftop helipad and communications spire.",
  },
  "academy-runway": {
    id: "academy-runway",
    name: "Central Flight Academy Runway",
    category: "airfield",
    regionId: "training",
    position: { x: 25, y: 1.2, z: -50 },
    elevationMsl: 1.2,
    callsign: "RWY-09-27",
    description: "260-meter paved airfield runway with threshold lighting and windsock station.",
  },
  "harbor-docks": {
    id: "harbor-docks",
    name: "Deepwater Cargo Terminal & Piers",
    category: "facility",
    regionId: "industrial",
    position: { x: 420, y: 1.5, z: 860 },
    elevationMsl: 1.5,
    callsign: "PORT-DOCKS",
    description: "Maritime shipping wharves with intermodal container cranes and ship moorings.",
  },
  "coastal-cliffs": {
    id: "coastal-cliffs",
    name: "Sentinel Bluffs & Sea Stack",
    category: "cliff",
    regionId: "coast",
    position: { x: -840, y: 22.0, z: 620 },
    elevationMsl: 22.0,
    callsign: "BLUFFS-SW",
    description: "Towering oceanic granite cliffs dropping sheer into crashing waves.",
  },
};

export const WATERWAY_DEFINITION: WaterwayDefinition = {
  lakeCenter: { x: -320, y: 8.5, z: -260 },
  lakeRadiusMeters: 110,
  waterfallLocation: { x: -270, y: 8.5, z: -210 },
  estuaryExit: { x: -80, y: 0.1, z: 920 },
  riverCenterline: [
    { x: -270, y: 8.5, z: -210 }, // Waterfall plunge
    { x: -250, y: 5.8, z: -170 }, // Upper canyon
    { x: -220, y: 4.5, z: -60 },  // Foothill gorge
    { x: -180, y: 3.2, z: 50 },   // Canyon bend
    { x: -140, y: 2.2, z: 160 },  // Beneath valley bridge
    { x: -120, y: 1.6, z: 320 },  // Lower valley
    { x: -100, y: 1.0, z: 520 },  // Plain transition
    { x: -90, y: 0.5, z: 720 },   // Delta widening
    { x: -80, y: 0.1, z: 920 },   // Ocean estuary mouth
  ],
};

export const ROAD_NETWORK_DEFINITION: RoadNetworkDefinition = {
  primaryHighways: [
    {
      id: "hwy-primary-metro",
      name: "Metropolis-Harbor Arterial Highway",
      type: "highway",
      widthMeters: 14,
      points: [
        { x: 640, y: 2.5, z: 240 },
        { x: 640, y: 2.5, z: 380 },
        { x: 580, y: 2.3, z: 540 },
        { x: 460, y: 2.0, z: 680 },
        { x: 380, y: 1.8, z: 780 },
        { x: 260, y: 1.5, z: 860 },
        { x: 60, y: 1.3, z: 880 },
      ],
    },
  ],
  connectors: [
    {
      id: "road-academy-city",
      name: "Academy-Metropolis Expressway",
      type: "arterial",
      widthMeters: 11,
      points: [
        { x: 50, y: 1.2, z: 0 },
        { x: 180, y: 1.4, z: 60 },
        { x: 360, y: 1.8, z: 160 },
        { x: 540, y: 2.2, z: 240 },
        { x: 640, y: 2.5, z: 320 },
      ],
    },
    {
      id: "road-academy-forest",
      name: "Whispering Pines Forest Road",
      type: "rural",
      widthMeters: 8,
      points: [
        { x: -180, y: 9.8, z: 140 }, // West bridge abutment junction
        { x: -300, y: 5.5, z: 70 },
        { x: -440, y: 4.8, z: 10 },
        { x: -620, y: 5.5, z: -40 },
      ],
    },
    {
      id: "road-pelican-connect",
      name: "Pelican Cove Coastal Spur",
      type: "rural",
      widthMeters: 8,
      points: [
        { x: -50, y: 1.2, z: 60 },
        { x: -75, y: 4.2, z: 120 },
        { x: -100, y: 9.8, z: 180 }, // East bridge abutment
      ],
    },
    {
      id: "road-west-pelican-spur",
      name: "West Pelican Coastal Highway",
      type: "rural",
      widthMeters: 8,
      points: [
        { x: -180, y: 9.8, z: 140 }, // West bridge abutment
        { x: -320, y: 4.5, z: 340 },
        { x: -540, y: 2.8, z: 480 },
        { x: -720, y: 2.0, z: 560 },
      ],
    },
  ],
  mountainPasses: [
    {
      id: "road-mountain-switchback",
      name: "Mount Apex Weather Station Pass",
      type: "switchback",
      widthMeters: 7.5,
      points: [
        { x: -80, y: 1.2, z: -80 },
        { x: -160, y: 3.5, z: -140 },
        { x: -180, y: 8.5, z: -210 },
        { x: -200, y: 14.0, z: -310 },
        { x: -260, y: 22.0, z: -390 },
        { x: -400, y: 32.0, z: -460 },
        { x: -500, y: 40.0, z: -510 },
        { x: -580, y: 48.0, z: -560 },
      ],
    },
  ],
  bridges: [
    {
      id: "bridge-valley",
      name: "Grand Valley Suspension Bridge",
      type: "bridge",
      widthMeters: 12,
      points: [
        { x: -100, y: 9.8, z: 180 },
        { x: -180, y: 9.8, z: 140 },
      ],
      hasBridge: true,
    },
  ],
};

export const WORLD_DEFINITION: WorldDefinition = {
  id: "drone-pilot-world-v1",
  name: "Archipelago Flight Proving Grounds",
  version: "1.0.0",
  terrain: TERRAIN_CONFIG,
  regions: REGIONS_RECORD,
  helipads: HELIPADS_RECORD,
  landmarks: LANDMARKS_RECORD,
  roads: ROAD_NETWORK_DEFINITION,
  waterways: WATERWAY_DEFINITION,
};
